### PR TITLE
Settings object with Pydantic

### PR DESCRIPTION
**Pull request by anschweitzer**
Setting read from environment and .env files with pydantic, and explicitly constructed and passed around, not automatically constructed on import.

**TL, DR**: Check out [config.py](https://github.com/anschweitzer/gw-scada-spaceheat-python/blob/main/gw_spaceheat/config.py) and [this](https://github.com/anschweitzer/gw-scada-spaceheat-python/blob/main/gw_spaceheat/actors/actor_base.py#L158) and [this](https://github.com/anschweitzer/gw-scada-spaceheat-python/blob/main/gw_spaceheat/command_line_utils.py#L74).

This PR is _probably_ ok to merge without much or any review, but it touches a lot of files and has some opinionated style changes which you might care about. 

Changes include:
- settings.py no longer used.
- [config.py](https://github.com/anschweitzer/gw-scada-spaceheat-python/blob/main/gw_spaceheat/config.py) contains settings classes.
- All config now read from either environment or .env files (environment overriding .env).
- Secrets are now read from the same .env file as other settings. We can discuss and change this choice. Without discussion, easy alternatives had subtle complications without obvious big win on security or usability.
- Renamed variables for case, scope and clarity since they are now part of an explicit object, not constants.
- The next PR will investigate passing the settings object rather than importing it, so we have greater control over when the setting are read.
- ActorBase, CloudBase and all desecendants now take a ScadaSettings object in their constructor. This is stored as a member variable and the settings are now accessed through the member variable, not through the imported module.
- run_nodes_main() and scripts that use it now have and use a parameter for a .env file.
- script functions use the .env file and environment to create a ScadaSettings object, which they pass along.
- Tests now automatically clear relevant environment variables before very test. See test/conftest.py, clean_scada_env() for details.
- load_house.load_all() now requires a passed in world_root_alias.
- The logging_on parameter was moved into ScadaSettings.
- Logging output directory taken from self.settings.
- mqttBroker, mqttBrokerPort self.gwMqttBroker and gwMqttBrokerPort are no longer member variables but are now accessed through self.settings.
- NodeConfig now takes a settings object.

The README is not yet updated. If the other changes look good to you (or we just decide to merge without review), I'll update README.

### CODE REVIEW

**Comment by anschweitzer** [comment]
FYI, this PR does not include changes to `README.md`. Those are necessary, but will be better made after further refactoring is done.

**Comment by anschweitzer** [comment]
PR also now includes a few protocol tests. To view only those changes, look [here](https://github.com/anschweitzer/gw-scada-spaceheat-python/pull/8).

Added:
* test_simple_sensor_value_update()
* test_power_meter_periodic_update()
* test_power_meter_aggregate_power_forward()
* A log_message_summary setting which turns on one-line message summary printing.
* test/show_protocol.py script which runs various protocol fragments.

**Review by jessicamillar — COMMENTED** [review]
looking forward to the merge

**Comment by anschweitzer** [comment]
Thanks for reminding me. I went to read about [typer](https://typer.tiangolo.com/) and got distracted.

**Pull request merged**
